name: 'Create a new releasae'

on: 
  push:
    branches:
      - main

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - uses: rymndhng/release-on-push-action@v0.28.0
        with:
          bump_version_scheme: patch
          tag_prefix: v