name: Terraform plan

on:
  workflow_call:
      inputs:
        working-directory:
          type: string
          default: "."
        workspace:
          type: string

jobs: 
    terraform-plan:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3

        - name: Configure google cloud Credentials
          uses: 'google-github-actions/auth@v2'
          with:
            project_id: ${{ secrets.GCP_PROJECT_ID }}
            workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
  

        - name: Terraform Plan
          if: ${{ inputs.workspace != 'default' }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            terraform init
            terraform workspace select -or-create ${{inputs.workspace}}
            terraform plan -var-file=./env/dev.tfvars -out=plan.tfplan
          working-directory: ${{inputs.working-directory}}

        - name: Terraform Plan Default Workspace
          if: ${{ inputs.workspace == 'default' }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            terraform init
            terraform plan -out=plan.tfplan
          working-directory: ${{inputs.working-directory}}

        - name: Upload Plan
          uses: actions/upload-artifact@v4
          with:
            name: plan-${{inputs.workspace}}
            path: ${{inputs.working-directory}}/plan.tfplan