name: Terraform pre-plan

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        default: "."

jobs:
  terraform-pre-plan:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure google cloud Credentials
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}


      - name: Terraform Init
        run: terraform init
        working-directory: ${{inputs.working-directory}}
      
      - name: Terraform Lint
        run: terraform fmt -check
        working-directory: ${{inputs.working-directory}}

      - name: Terraform Format
        run: terraform fmt
        working-directory: ${{inputs.working-directory}}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{inputs.working-directory}}